/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wlvp.ParkPass;

import java.util.ArrayList;
import wlvp.AccountCreation.Guest;

/**
 *
 * @author Daniel
 */
public class ParkPassView extends javax.swing.JFrame {
    private ParkPassController parkPassController;
    private ArrayList<Guest> guestList;
    private ParkPass parkPass;
    /**
     * Creates new form ParkPassView
     */
    public ParkPassView(ParkPassController parkPassController) {
        this.parkPassController = parkPassController;
        initComponents();
        this.parkPass = parkPassController.getParkPass();
        parsePass(parkPass);
        
    }
    public void parsePass(ParkPass parkPass){
        creditTextField.setText(parkPass.getCredits()+ "");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parkPassPanel = new javax.swing.JPanel();
        parkPassLabel = new javax.swing.JLabel();
        creditsLabel = new javax.swing.JLabel();
        creditTextField = new javax.swing.JTextField();
        addCreditsButton = new javax.swing.JButton();
        toItineraryButton = new javax.swing.JButton();
        toAccountButton = new javax.swing.JButton();
        viewUserList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guestListView = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        parkPassLabel.setFont(new java.awt.Font("Kailasa", 1, 14)); // NOI18N
        parkPassLabel.setText("Park Pass");
        parkPassLabel.setToolTipText("");
        parkPassLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        creditsLabel.setText("Credit Amount");

        creditTextField.setText("0.00");

        addCreditsButton.setText("Add Credits");

        toItineraryButton.setText("Itinerary");

        toAccountButton.setText("Account");

        viewUserList.setText("Refresh");

        guestListView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(guestListView);

        javax.swing.GroupLayout parkPassPanelLayout = new javax.swing.GroupLayout(parkPassPanel);
        parkPassPanel.setLayout(parkPassPanelLayout);
        parkPassPanelLayout.setHorizontalGroup(
            parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkPassPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parkPassPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(36, 36, 36))
                    .addGroup(parkPassPanelLayout.createSequentialGroup()
                        .addGroup(parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parkPassPanelLayout.createSequentialGroup()
                                .addComponent(creditsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(parkPassPanelLayout.createSequentialGroup()
                                .addComponent(toAccountButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parkPassLabel)
                                .addGap(16, 16, 16)))
                        .addGroup(parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toItineraryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCreditsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
            .addGroup(parkPassPanelLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(viewUserList)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        parkPassPanelLayout.setVerticalGroup(
            parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parkPassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkPassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toAccountButton)
                    .addComponent(toItineraryButton))
                .addGap(25, 25, 25)
                .addGroup(parkPassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditsLabel)
                    .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCreditsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewUserList)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parkPassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parkPassPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addCreditsButton;
    private javax.swing.JTextField creditTextField;
    private javax.swing.JLabel creditsLabel;
    private javax.swing.JList<String> guestListView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel parkPassLabel;
    private javax.swing.JPanel parkPassPanel;
    public javax.swing.JButton toAccountButton;
    private javax.swing.JButton toItineraryButton;
    public javax.swing.JButton viewUserList;
    // End of variables declaration//GEN-END:variables
}
