package wlvp.AccountCreation;

import javax.swing.JOptionPane;
import wlvp.ParkPass.ParkPassController;

/**
 *
 * @author alanb
 */
public class AccountCreationView extends javax.swing.JFrame {

    /**
     * Creates new form AccountCreationView
     */
    public AccountCreationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JTextField();
        createAccountButton = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        accountLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        accountLabel.setText("Email");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        createAccountButton.setText("Create New");
        createAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountButtonActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("WELCOME TO WLVP!");

        loginButton.setText("Log In");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(accountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 176, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordLabel)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(emailTextField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createAccountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAccountButton)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        String email = emailTextField.getText();
        if (AccountController.isEmailValid(email)) {
            JOptionPane.showMessageDialog(this, "Email is valid.");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid email format. Please try again.");
        }
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        String password = passwordTextField.getText();
        if (AccountController.isPasswordValid(password)) {
            JOptionPane.showMessageDialog(this, "Password is valid.");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid password. Password must be 8-24 characters and contain at least 3 alphanumeric characters.");
        }
    }//GEN-LAST:event_passwordTextFieldActionPerformed


    private void createAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountButtonActionPerformed
        String email = emailTextField.getText();
        String password = passwordTextField.getText();

        // Check email validity
        boolean isEmailValid = AccountController.isEmailValid(email);
        // Check password validity
        boolean isPasswordValid = AccountController.isPasswordValid(password);

        // Provide specific feedback for validation errors
        if (!isEmailValid && !isPasswordValid) {
            JOptionPane.showMessageDialog(this,
                    "Both email and password are invalid.\n"
                    + "- Email must include '@' and a domain, and be under 16 characters.\n"
                    + "- Password must be 8-24 characters, with at least 3 alphanumeric characters.",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!isEmailValid) {
            JOptionPane.showMessageDialog(this,
                    "Invalid email format. Please ensure it includes '@' and a domain, and is under 16 characters.",
                    "Invalid Email",
                    JOptionPane.ERROR_MESSAGE);
        } else if (!isPasswordValid) {
            JOptionPane.showMessageDialog(this,
                    "Invalid password format. Password must be 8-24 characters long and contain at least 3 alphanumeric characters.",
                    "Invalid Password",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            // If both are valid, proceed with account creation
            AccountController.createGuest(email, password); // Assuming this is a guest user (type null)
            ParkPassController.navigateToParkPass();
            JOptionPane.showMessageDialog(this, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_createAccountButtonActionPerformed


    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String email = emailTextField.getText();
        String password = passwordTextField.getText();
        AbstractUser user = AccountController.login(email, password);

        if (user == null) {
            JOptionPane.showMessageDialog(this, "Invalid login credentials.", "Invalid Credentials", JOptionPane.ERROR_MESSAGE);
        } else {
            Class<?> userType = user.getClass();
            if (userType.isAssignableFrom(Guest.class)) {
                // User is a Guest
                ParkPassController.navigateToParkPass();
            } else if (userType.isAssignableFrom(Employee.class)) {
                // User is an Employee
                
            }
        }
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JButton createAccountButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
